console.log('Number of brothers I have!')
console.log(1)
console.log('Number of sisters I have!')
console.log(0)
console.log('The year of our birth is!')
console.log('1991!')
console.log('The number of brothers and sisters I have together!')
console.log(1+0)
console.log('Our age is!')
console.log(2018-1992)
//Concatenation
console.log('I have ' + (1 + 0) +  ' sibling and it\'s been ' + (2018 - 1992) +  ' years since the year we were born!')
//This is a much cleaner way using tilde button instead of quotes (Interpolation)
console.log(`I have ${1+0} sibling and it\'s been ${2018-1992} years since the year we were born!`)
